version: '3.0'

services:
  grafana:
    container_name: 'business-intelligence'
    build:
      context: ./.config
    ports:
      - 3000:3000/tcp
    environment:
      - GF_INSTALL_PLUGINS=marcusolsson-csv-datasource
      - GF_PLUGIN_ALLOW_LOCAL_MODE=true
      - GF_DATABASE_HOST=grafana_db:3306
      - GF_DATABASE_NAME=grafana
      - GF_DATABASE_USER=grafana
      - GF_DATABASE_PASSWORD=${GF_DATABASE_PASSWORD}
      - GF_DATABASE_TYPE=mysql
      - GF_DATABASE_MAX_OPEN_CONN=300
    volumes:
      - ./provisioning:/etc/grafana/provisioning
      - ./data:/data
      - grafana-storage:/var/lib/grafana
    env_file:
      - .env
    depends_on:
      - grafana_db
  
  go-backend:
    build:
      context: .
      dockerfile: cmd/backend/Dockerfile
    environment:
      - MYSQL_HOST=grafana_db:3306
      - MYSQL_DATABASE=grafana
      - MYSQL_USER=grafana
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 2112:2112
    env_file:
      - .env
    depends_on:
      - grafana_db

  grafana_db:
    container_name: 'grafana_mysql_db'
    image: mysql:8.0
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=grafana
      - MYSQL_USER=grafana
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    command:
      [
        mysqld,
        --character-set-server=utf8mb4,
        --collation-server=utf8mb4_unicode_ci,
        --innodb_monitor_enable=all,
        --max-connections=1001,
      ]
    ports:
      - 3306:3306
volumes:
  grafana-storage: